//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityfwDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeedetail
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public int DeptId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> totalsalary { get; set; }
    }
}
